name: Development Tests

on:
  push:
    branches:
      - 'development'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv